import random

# Write your error handling block here
def main():
    try:
        print(random.randinteger(5,15))
    except AttributeError:
        print("Double check the attributes in your code and try again.")
    

if __name__ == '__main__':
    main()
